### ISSUE TITLE
500 error when user enters invalid email address

### ISSUE THREAD

**Issue by Rossiar** [AndrewGorton/DigitalMarketplaceAlerter#11]
![image](https://cloud.githubusercontent.com/assets/1635940/19687349/f842b85e-9abc-11e6-9412-669df4d7e399.png)

The above is seen on the `alert/` screen, when adding an email that is not valid, the logs: 
![image](https://cloud.githubusercontent.com/assets/1635940/19687407/31fb57f4-9abd-11e6-966b-91b36303a3be.png)

This evaluation code should fail more elegantly, perhaps with an error message for the user and a redirect? @AndrewGorton to advise on best practice here

**Comment by AndrewGorton** [comment]
I agree - it should fail in a more user-friendly approach.

**Comment by AndrewGorton** [comment]
Worth looking at the ForbiddenExceptionMapper and replicate that kind of exception-to-view plumbing.
